project_id = "minuto-106"

[functions.game-api]
verify_jwt = false

[functions.game-ready-api]
verify_jwt = false

[functions.league-api]
verify_jwt = false

[functions.player-share]
verify_jwt = false

[functions.social-share]
verify_jwt = false

[functions.player-context]
verify_jwt = false
