import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const edgeCard = readFileSync('supabase/functions/player-share/index.ts', 'utf8');
const browserRadar = readFileSync('public/player-stats.js', 'utf8');
const playerPage = readFileSync('public/player.js', 'utf8');
const playerShell = readFileSync('public/player.html', 'utf8');
const playerUi = readFileSync('public/player-ui.js', 'utf8');
const shareIntegration = readFileSync('scripts/test-player-share-local.mjs', 'utf8');
const edgeRadarElement = edgeCard.slice(edgeCard.indexOf('function radarElement'), edgeCard.indexOf('function flagElement'));

describe('player card radar parity', () => {
  it('delegates browser and generated cards to the canonical model', () => {
    expect(browserRadar).toContain('window.Minuto106PlayerRadarModel');
    expect(browserRadar).toContain('radarModel.buildRadarStats');
    expect(browserRadar).not.toContain('precisionMaximumDifferenceMs: 1000');
    expect(browserRadar).not.toContain('verifiedAttempts / lifetimeAttemptsUsed');

    expect(edgeCard).toContain("from '../_shared/player-radar-model.js'");
    expect(edgeCard).toContain('playerRadarStatsArray(profile)');
    expect(edgeCard).not.toContain('function radarStats(');
    expect(edgeCard).not.toContain('completedReferrals * 20 + bonusAttempts * 8');
  });

  it('loads the same lifetime profile contract as the browser', () => {
    expect(edgeCard).toContain("supabase.rpc('get_game_player_profile'");
    expect(edgeCard).not.toContain("supabase.rpc('get_game_public_profile'");
    expect(shareIntegration).toContain("/rest/v1/rpc/get_game_player_profile");
    expect(shareIntegration).toContain('lifetimeAttemptsUsed');
  });

  it('versions every player card by data and renderer revision', () => {
    expect(playerShell.indexOf('player-radar-model.js')).toBeLessThan(playerShell.indexOf('player-ui.js'));
    expect(playerUi).toContain("edgeUrl.searchParams.set('v'");
    expect(playerUi).toContain("edgeUrl.searchParams.set('r'");
    expect(playerUi).toContain('Minuto106PlayerRadarModel?.cardRendererRevision');
    expect(edgeCard).toContain("url.searchParams.set('v'");
    expect(edgeCard).toContain("url.searchParams.set('r', String(PLAYER_CARD_RENDERER_REVISION))");
    expect(edgeCard).toContain("'X-Minuto106-Card-Renderer': String(PLAYER_CARD_RENDERER_REVISION)");
    expect(shareIntegration).toContain("searchParams.get('r')");
    expect(shareIntegration).toContain("headers.get('x-minuto106-card-renderer')");
  });

  it('renders the same five-level labelled radar structure as the web profile', () => {
    expect(edgeCard).toContain('const RADAR_LABELS');
    expect(edgeRadarElement).toContain('for (const level of [20, 40, 60, 80, 100])');
    expect(edgeRadarElement).toContain("h('line'");
    expect(edgeRadarElement).toContain("h('circle'");
    expect(edgeRadarElement).toContain('truncate(nick, 18)');
    expect(edgeRadarElement).toContain('axis.justifyContent');
    expect(edgeRadarElement).not.toContain("h('text'");
    expect(edgeCard).not.toContain('`${label} ${stats[index]}`');
  });

  it('persists the overview PNG generated by the local Edge integration', () => {
    expect(shareIntegration).toContain('/card.png');
    expect(shareIntegration).toContain("persistPreview('player-overview.png'");
  });
});

describe('clean player route navigation', () => {
  it('normalizes shared chrome links after replacing the visible URL', () => {
    expect(playerPage).toContain('function normalizeSiteChromeLinks()');
    expect(playerPage).toContain(".site-header a[href], .site-footer a[href], #cookieBanner a[href]");
    expect(playerPage).toContain('new URL(href, appBaseUrl).toString()');
    expect(playerPage.indexOf('history.replaceState')).toBeLessThan(playerPage.indexOf('normalizeSiteChromeLinks();'));
  });
});
