import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const edgeCard = readFileSync('supabase/functions/player-share/index.ts', 'utf8');
const browserRadar = readFileSync('public/player-stats.js', 'utf8');
const playerPage = readFileSync('public/player.js', 'utf8');
const shareIntegration = readFileSync('scripts/test-player-share-local.mjs', 'utf8');
const edgeRadarStats = edgeCard.slice(edgeCard.indexOf('function radarStats'), edgeCard.indexOf('function radarPoint'));

describe('player card radar parity', () => {
  it('uses the browser impact inputs instead of achievement points', () => {
    for (const source of [browserRadar, edgeRadarStats]) {
      expect(source).toContain('completedReferrals');
      expect(source).toContain('bonusAttempts');
      expect(source).toContain('completedReferrals * 20 + bonusAttempts * 8');
    }
    expect(edgeRadarStats).not.toContain('achievements');
  });

  it('renders the same five-level labelled radar structure as the web profile', () => {
    expect(edgeCard).toContain('const RADAR_LABELS');
    expect(edgeCard).toContain('for (const level of [20, 40, 60, 80, 100])');
    expect(edgeCard).toContain("h('line'");
    expect(edgeCard).toContain("h('text'");
    expect(edgeCard).toContain("h('circle'");
    expect(edgeCard).toContain('truncate(nick, 18)');
    expect(edgeCard).not.toContain('`${label} ${stats[index]}`');
  });

  it('persists the overview PNG generated by the local Edge integration', () => {
    expect(shareIntegration).toContain('/card.png');
    expect(shareIntegration).toContain("persistPreview('player-overview.png'");
  });
});

describe('clean player route navigation', () => {
  it('normalizes shared chrome links after replacing the visible URL', () => {
    expect(playerPage).toContain('function normalizeSiteChromeLinks()');
    expect(playerPage).toContain(".site-header a[href], .site-footer a[href], #cookieBanner a[href]");
    expect(playerPage).toContain('new URL(href, appBaseUrl).toString()');
    expect(playerPage.indexOf('history.replaceState')).toBeLessThan(playerPage.indexOf('normalizeSiteChromeLinks();'));
  });
});
